package com.greencloud.entity;

// Generated 2014-4-22 15:13:09 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * UserAuthCfgRoleCard generated by hbm2java
 */
public class UserAuthCfgRoleCard extends OperationInfo {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3246538367974387308L;
	
	private String roleCode;
	private String cardTypeCodes;


	public UserAuthCfgRoleCard() {
	}

	public UserAuthCfgRoleCard(Long hotelGroupId, Long hotelId,
			String roleCode, String cardTypeCodes, String createUser,
			Date createDatetime, String modifyUser, Date modifyDatetime) {
		this.hotelGroupId = hotelGroupId;
		this.hotelId = hotelId;
		this.roleCode = roleCode;
		this.cardTypeCodes = cardTypeCodes;
		this.createUser = createUser;
		this.createDatetime = createDatetime;
		this.modifyUser = modifyUser;
		this.modifyDatetime = modifyDatetime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getHotelGroupId() {
		return this.hotelGroupId;
	}

	public void setHotelGroupId(Long hotelGroupId) {
		this.hotelGroupId = hotelGroupId;
	}

	public Long getHotelId() {
		return this.hotelId;
	}

	public void setHotelId(Long hotelId) {
		this.hotelId = hotelId;
	}

	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public String getCardTypeCodes() {
		return this.cardTypeCodes;
	}

	public void setCardTypeCodes(String cardTypeCodes) {
		this.cardTypeCodes = cardTypeCodes;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	public String getModifyUser() {
		return this.modifyUser;
	}

	public void setModifyUser(String modifyUser) {
		this.modifyUser = modifyUser;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

}
