package com.greencloud.entity;


//Generated 2014-10-31 9:50:25 by Hibernate Tools 3.4.0.CR1


/**
* TpStoreSubclass generated by hbm2java
*/
public class PosStoreSubclass extends OperationInfo {

	/**
	 * 
	 */
	private static final long serialVersionUID = 52861541069226931L;
	private String code;
	private String name;
	private String engName;
	private String cseg;
	private String cname;
	private String cstype;
	private String engCname;
	
	private String isGroup;
	private String groupCode;
	private String codeType;
	public String getIsGroup() {
		return isGroup;
	}
	public void setIsGroup(String isGroup) {
		this.isGroup = isGroup;
	}
	public String getGroupCode() {
		return groupCode;
	}
	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode;
	}
	public String getCodeType() {
		return codeType;
	}
	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}
	
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getEngName() {
		return engName;
	}
	public void setEngName(String engName) {
		this.engName = engName;
	}
	public String getCseg() {
		return cseg;
	}
	public void setCseg(String cseg) {
		this.cseg = cseg;
	}
	public String getCname() {
		return cname;
	}
	public void setCname(String cname) {
		this.cname = cname;
	}
	public String getCstype() {
		return cstype;
	}
	public void setCstype(String cstype) {
		this.cstype = cstype;
	}
	public String getEngCname() {
		return engCname;
	}
	public void setEngCname(String engCname) {
		this.engCname = engCname;
	}
	
}
