/*
 -- 生成新餐饮预订、开台、账单 单号生成规则配置
delete from sys_extra_id where code in ('POSRSV','POSMASTER','POSBILL');
insert into `sys_extra_id` (`hotel_group_id`, `hotel_id`,`code`, `descript`, `descript_en`, `pointer_type`, `prefix1`, `prefix2`, `prefix3`, `pos_cur`, `pos_begin`, `pos_interval`, `pos_max`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) 
values('2','-1','POSRSV','餐饮预订号','Pos.Rsv','DAY','','','','1','1','1','10000','F','0','ADMIN','2015-04-01 09:57:17','ADMIN','2015-04-07 16:04:33');
insert into `sys_extra_id` (`hotel_group_id`, `hotel_id`,`code`, `descript`, `descript_en`, `pointer_type`, `prefix1`, `prefix2`, `prefix3`, `pos_cur`, `pos_begin`, `pos_interval`, `pos_max`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) 
SELECT t2.hotel_group_id,t2.id,t1.CODE,t1.descript,t1.descript_en,t1.pointer_type,t1.prefix1,t1.prefix2,t1.prefix3,t1.pos_cur,t1.pos_begin,t1.pos_interval,t1.pos_max,t1.is_halt,t1.list_order,t1.create_user,t1.create_datetime,t1.modify_user,t1.modify_datetime
FROM sys_extra_id t1,hotel t2
WHERE t1.hotel_id=-1;
DELETE FROM sys_extra_id WHERE hotel_id=-1;
insert into `sys_extra_id` (`hotel_group_id`, `hotel_id`,`code`, `descript`, `descript_en`, `pointer_type`, `prefix1`, `prefix2`, `prefix3`, `pos_cur`, `pos_begin`, `pos_interval`, `pos_max`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) 
values('2','-1','POSMASTER','餐饮主单号','Pos.Master','DAY','','','','1','1','1','10000','F','0','ADMIN','2015-04-01 09:57:17','ADMIN','2015-04-07 16:04:33');
insert into `sys_extra_id` (`hotel_group_id`, `hotel_id`,`code`, `descript`, `descript_en`, `pointer_type`, `prefix1`, `prefix2`, `prefix3`, `pos_cur`, `pos_begin`, `pos_interval`, `pos_max`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) 
SELECT t2.hotel_group_id,t2.id,t1.CODE,t1.descript,t1.descript_en,t1.pointer_type,t1.prefix1,t1.prefix2,t1.prefix3,t1.pos_cur,t1.pos_begin,t1.pos_interval,t1.pos_max,t1.is_halt,t1.list_order,t1.create_user,t1.create_datetime,t1.modify_user,t1.modify_datetime
FROM sys_extra_id t1,hotel t2
WHERE t1.hotel_id=-1;
DELETE FROM sys_extra_id WHERE hotel_id=-1;
insert into `sys_extra_id` (`hotel_group_id`, `hotel_id`,`code`, `descript`, `descript_en`, `pointer_type`, `prefix1`, `prefix2`, `prefix3`, `pos_cur`, `pos_begin`, `pos_interval`, `pos_max`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) 
values('2','-1','POSBILL','餐饮账单号','Pos.Bill','DAY','','','','1','1','1','10000','F','0','ADMIN','2015-04-01 09:57:17','ADMIN','2015-04-07 16:04:33');
insert into `sys_extra_id` (`hotel_group_id`, `hotel_id`,`code`, `descript`, `descript_en`, `pointer_type`, `prefix1`, `prefix2`, `prefix3`, `pos_cur`, `pos_begin`, `pos_interval`, `pos_max`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) 
SELECT t2.hotel_group_id,t2.id,t1.CODE,t1.descript,t1.descript_en,t1.pointer_type,t1.prefix1,t1.prefix2,t1.prefix3,t1.pos_cur,t1.pos_begin,t1.pos_interval,t1.pos_max,t1.is_halt,t1.list_order,t1.create_user,t1.create_datetime,t1.modify_user,t1.modify_datetime
FROM sys_extra_id t1,hotel t2
WHERE t1.hotel_id=-1;
DELETE FROM sys_extra_id WHERE hotel_id=-1;
*/
 -- 使用存储过程  生成 未定义的酒店的  餐饮预订、开台、账单 单号生成规则配置
DELIMITER $$

DROP PROCEDURE IF EXISTS add_sys_extra_id_pos $$

CREATE DEFINER=`root`@`%` PROCEDURE `add_sys_extra_id_pos`()
    SQL SECURITY INVOKER
BEGIN



    DROP TEMPORARY TABLE IF EXISTS tmp_pos_hotel;
	CREATE TEMPORARY TABLE tmp_pos_hotel (
		hotel_group_id 		BIGINT(16) NOT NULL,
		hotel_id 		BIGINT(16) NOT NULL,
		id 			BIGINT(16) NOT NULL AUTO_INCREMENT,
		PRIMARY KEY (id)
  ) ;
    -- 检查到hotel中还未配置的酒店ID 
    INSERT INTO tmp_pos_hotel(hotel_group_id,hotel_id)
		SELECT c.hotel_group_id,c.id  FROM 
		(
			SELECT a.hotel_group_id,a.id,b.hotel_group_id as hotel_group_id_2 ,b.hotel_id as hotel_id_2 FROM hotel a 
			LEFT JOIN 
			(SELECT hotel_group_id, hotel_id  FROM sys_extra_id WHERE `code` IN ('POSRSV','POSMASTER','POSBILL') GROUP BY hotel_group_id,hotel_id) b
			ON a.hotel_group_id = b.hotel_group_id AND a.id = b.hotel_id 
		) c
		WHERE c.hotel_id_2 IS NULL ;
   -- 生成新餐饮预订、开台、账单 单号生成规则配置
		delete from sys_extra_id where code in ('POSRSV','POSMASTER','POSBILL') AND hotel_id = '-1' ;

		insert into `sys_extra_id` (`hotel_group_id`, `hotel_id`,`code`, `descript`, `descript_en`, `pointer_type`, `prefix1`, `prefix2`, `prefix3`, `pos_cur`, `pos_begin`, `pos_interval`, `pos_max`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) 
		values('2','-1','POSRSV','餐饮预订号','Pos.Rsv','DAY','','','','1','1','1','10000','F','0','ADMIN','2015-04-01 09:57:17','ADMIN','2015-04-07 16:04:33');
		insert into `sys_extra_id` (`hotel_group_id`, `hotel_id`,`code`, `descript`, `descript_en`, `pointer_type`, `prefix1`, `prefix2`, `prefix3`, `pos_cur`, `pos_begin`, `pos_interval`, `pos_max`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) 
		SELECT t2.hotel_group_id,t2.hotel_id,t1.CODE,t1.descript,t1.descript_en,t1.pointer_type,t1.prefix1,t1.prefix2,t1.prefix3,t1.pos_cur,t1.pos_begin,t1.pos_interval,t1.pos_max,t1.is_halt,t1.list_order,t1.create_user,t1.create_datetime,t1.modify_user,t1.modify_datetime
		FROM sys_extra_id t1,tmp_pos_hotel t2
		WHERE t1.hotel_id=-1;
		DELETE FROM sys_extra_id WHERE hotel_id=-1;

		insert into `sys_extra_id` (`hotel_group_id`, `hotel_id`,`code`, `descript`, `descript_en`, `pointer_type`, `prefix1`, `prefix2`, `prefix3`, `pos_cur`, `pos_begin`, `pos_interval`, `pos_max`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) 
		values('2','-1','POSMASTER','餐饮主单号','Pos.Master','DAY','','','','1','1','1','10000','F','0','ADMIN','2015-04-01 09:57:17','ADMIN','2015-04-07 16:04:33');
		insert into `sys_extra_id` (`hotel_group_id`, `hotel_id`,`code`, `descript`, `descript_en`, `pointer_type`, `prefix1`, `prefix2`, `prefix3`, `pos_cur`, `pos_begin`, `pos_interval`, `pos_max`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) 
		SELECT t2.hotel_group_id,t2.hotel_id,t1.CODE,t1.descript,t1.descript_en,t1.pointer_type,t1.prefix1,t1.prefix2,t1.prefix3,t1.pos_cur,t1.pos_begin,t1.pos_interval,t1.pos_max,t1.is_halt,t1.list_order,t1.create_user,t1.create_datetime,t1.modify_user,t1.modify_datetime
		FROM sys_extra_id t1,tmp_pos_hotel t2
		WHERE t1.hotel_id=-1;
		DELETE FROM sys_extra_id WHERE hotel_id=-1;

		insert into `sys_extra_id` (`hotel_group_id`, `hotel_id`,`code`, `descript`, `descript_en`, `pointer_type`, `prefix1`, `prefix2`, `prefix3`, `pos_cur`, `pos_begin`, `pos_interval`, `pos_max`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) 
		values('2','-1','POSBILL','餐饮账单号','Pos.Bill','DAY','','','','1','1','1','10000','F','0','ADMIN','2015-04-01 09:57:17','ADMIN','2015-04-07 16:04:33');
		insert into `sys_extra_id` (`hotel_group_id`, `hotel_id`,`code`, `descript`, `descript_en`, `pointer_type`, `prefix1`, `prefix2`, `prefix3`, `pos_cur`, `pos_begin`, `pos_interval`, `pos_max`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) 
		SELECT t2.hotel_group_id,t2.hotel_id,t1.CODE,t1.descript,t1.descript_en,t1.pointer_type,t1.prefix1,t1.prefix2,t1.prefix3,t1.pos_cur,t1.pos_begin,t1.pos_interval,t1.pos_max,t1.is_halt,t1.list_order,t1.create_user,t1.create_datetime,t1.modify_user,t1.modify_datetime
		FROM sys_extra_id t1,tmp_pos_hotel t2
		WHERE t1.hotel_id=-1;
		DELETE FROM sys_extra_id WHERE hotel_id=-1;
		
		
		DROP TEMPORARY TABLE IF EXISTS tmp_pos_hotel; 
	-- 
    END$$

DELIMITER ;

CALL add_sys_extra_id_pos();

DROP PROCEDURE IF EXISTS add_sys_extra_id_pos ;

-- 权限代码生成
truncate table user_pos_auth;
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','posMode','0','模块设置','模块设置',NULL,'F','0','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','posSystemGroup','0','集团系统设置','集团系统设置',NULL,'F','0','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','posSystem','0','系统设置','系统设置',NULL,'F','0','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','posSystemLocal','0','本地设置','本地设置',NULL,'F','0','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','posCashier','0','收银设置','收银设置',NULL,'F','0','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','posOrder','0','点菜设置','点菜设置',NULL,'F','0','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','posRes','0','预订设置','预订设置',NULL,'F','0','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posMode!Cashier','posMode','综合收银','综合收银',NULL,'F','1001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posMode!System','posMode','系统维护','系统维护',NULL,'F','1001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posMode!SystemLocal','posMode','本地维护','本地维护',NULL,'F','1001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posOrder!create','posOrder','新开单','新开单',NULL,'F','6001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posOrder!order','posOrder','点菜下单','点菜下单',NULL,'F','6001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posOrder!delete','posOrder','退菜','退菜',NULL,'F','6001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posOrder!orderOffline','posOrder','离线点菜','离线点菜',NULL,'F','6001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!masterEdit','posCashier','主单信息修改','主单信息修改',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!link','posCashier','联单','联单',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!change','posCashier','换桌','换桌',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!merger','posCashier','并桌','并桌',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!revoke','posCashier','消单','消单',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!pluDsc','posCashier','单菜折扣','单菜折扣',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!pluEnt','posCashier','单菜赠送','单菜赠送',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!YJbill','posCashier','预结单打印','预结单打印',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!bill','posCashier','账单打印','账单打印',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!checkOut','posCashier','结账','结账',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!res','posCashier','预订详情','预订详情',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!resOpen','posCashier','预订转登记','预订转登记',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!report','posCashier','交班报表','交班报表',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!checkRe','posCashier','撤销结账','撤销结账',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!checkS','posCashier','挂S账','挂S账',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!checkReC','posCashier','重登','重登',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!syncUp','posCashier','云同步','云同步',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!audit','posCashier','夜间稽核','夜间稽核',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!access','posCashier','沽清设置','沽清设置',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!accessDel','posCashier','沽清取消','沽清取消',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!station','posCashier','站点管理','站点管理',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!getData','posCashier','数据更新','数据更新',NULL,'F','7001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posRes!resList','posRes','预订列表查询','预订列表查询',NULL,'F','5001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posRes!res','posRes','新建预订','新建预订',NULL,'F','5001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posRes!resEdit','posRes','预订主单修改','预订主单修改',NULL,'F','5001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posRes!resPlu','posRes','预订菜式','预订菜式',NULL,'F','5001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posRes!resPay','posRes','预定金','预定金',NULL,'F','5001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posRes!resDel','posRes','预订取消','预订取消',NULL,'F','5001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posRes!resRe','posRes','预订恢复','预订恢复',NULL,'F','5001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posRes!resPayList','posRes','定金列表','定金列表',NULL,'F','5001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posSystemGroup!code','posSystemGroup','基本代码设置','基本代码设置',NULL,'F','2001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posSystem!mode','posSystem','模式设置','模式设置',NULL,'F','3001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posSystemGroup!pluE','posSystemGroup','菜谱编辑','菜谱编辑',NULL,'F','2001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posSystemGroup!condst','posSystemGroup','做法设置','做法设置',NULL,'F','2001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posSystemGroup!sysopt','posSystemGroup','参数设置','参数设置',NULL,'F','2001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posSystemGroup!report','posSystemGroup','集团报表','集团报表',NULL,'F','2001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posSystem!code','posSystem','代码设置','代码设置',NULL,'F','3001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posSystem!pluE','posSystem','菜谱设置','菜谱设置',NULL,'F','3001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posSystem!pccode','posSystem','营业点设置','营业点设置',NULL,'F','3001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posSystem!report','posSystem','酒店报表','酒店报表',NULL,'F','3001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posSystem!master','posSystem','餐单查询','餐单查询',NULL,'F','3001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posSystemGroup!master','posSystemGroup','餐单查询','餐单查询',NULL,'F','2001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posSystem!editAuth','posSystem','权限设置','权限设置',NULL,'F','3001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posSystemLocal!print','posSystemLocal','厨打设置','厨打设置',NULL,'F','4001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posSystemLocal!interf','posSystemLocal','接口设置','接口设置',NULL,'F','4001','ADMIN','2015-11-25 17:21:21','ADMIN','2015-11-25 17:21:21');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posCashier!SstaChange','posCashier','S状态下修改','S状态下修改',NULL,'F','7001','ADMIN','2016-03-24 11:27:00','ADMIN','2016-03-24 11:27:06');
insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','pos','pos!posOrder!writeOff','posOrder','冲销菜品','冲销菜品',NULL,'F','6001','ADMIN','2016-03-24 11:27:00','ADMIN','2016-03-24 11:27:06');

insert into `user_pos_auth` (`hotel_group_id`, `hotel_id`, `app_code`, `code`, `parent_code`, `descript`, `descript_en`, `auth_flag`, `is_halt`, `list_order`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`)
SELECT t2.hotel_group_id,t2.id,t1.app_code,t1.code,t1.parent_code,t1.descript,t1.descript_en,t1.auth_flag,t1.is_halt,t1.list_order,t1.create_user,t1.create_datetime,t1.modify_user,t1.modify_datetime
FROM user_pos_auth t1,hotel t2
WHERE t1.hotel_id=-1;
DELETE FROM user_pos_auth WHERE hotel_id=-1;


-- 加入日志配置
delete from log_info_config where entity_name = 'POS_RES' or entity_name = 'POS_MASTER' ;
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','RES_NAME','预订名称','res_name','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','PCCODE','营业点','pccode','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','MODE','模式','mode','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','STA','状态','sta','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','SHIFT','班次','shift','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','TABLENO','桌号','tableno','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','EXTTABLENO','辅桌','exttableno','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','BIZ_DATE','营业日期','biz_date','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','RES_NAME','预订名称','res_name','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','HOTEL_ID','酒店id','hotel_id','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','ACCNT','单号','accnt','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','TYPE1','类别1','type1','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','TYPE2','类别2','type2','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','TYPE3','类别3','type3','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','TYPE4','类别4','type4','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','TYPE5','类别5','type5','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','EMPID','工号','empid','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','OSTA',' 上次状态','osta','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','RES_DATE','预订日期','res_date','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','TABLE_TYPE','桌号类别','table_type','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','NUMB','桌数','numb','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','GSTS','客人数','gsts','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','CHILDREN','儿童数','children','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','MARKET','市场码','market','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','SOURCE','来源码','source','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','HACCNT','关联客户档案号','haccnt','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','NAME','关联客户姓名','name','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','CUSNO','协议单位号','cusno','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','CUSINFO','协议单位名称','cusinfo','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','CARDNO','贵宾卡号','cardno','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','CARDINFO','贵宾卡名称','cardinfo','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','SALEID','销售代码','saleid','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','SALEINFO','销售员信息','saleinfo','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','PHONE','预订电话','phone','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','EMAIL','email','email','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','BEGIN_TIME','预订时间点 exp:1200','begin_time','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','END_TIME','截止时间点 exp:1600','end_time','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','ARRTIME','到达时间','arrtime','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','AMOUNT','标准金额','amount','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','TYPE','A/按桌 B/按人','type','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','PAYTYPE','付款方式 RMB现付，TAR挂账，OTH其他','paytype','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','PAY','定金金额','pay','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','CHARGE','消费金额','charge','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','TOACCNT','批量单号','toaccnt','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','ACCNTINFO','挂账单位信息','accntinfo','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','CMSCODE','佣金代码','cmscode','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','INFO','主单备注信息','info','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','LOVE','客人喜好','love','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_RES','QR_CODE','二维码 网站二维码','qr_code','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','TYPE1','类别1','type1','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','TYPE2','类别2','type2','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','TYPE3','类别3','type3','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','TYPE4','类别4','type4','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','TYPE5','类别5','type5','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','PCCODE','营业点代码','pccode','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','MODE','模式代码','mode','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','SHIFT','班别','shift','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','EMPID','工号','empid','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','STA','状态','sta','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','OSTA','上次状态','osta','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','BIZ_DATE','营业日期','biz_date','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','TABLENO','桌号','tableno','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','EXTTABLENO','扩展桌号','exttableno','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','GSTS','客人数','gsts','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','CHILDREN','儿童数','children','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','PHONE','预订电话','phone','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','MARKET','市场码','market','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','SOURCE','来源码','source','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','HACCNT','关联客户档案号','haccnt','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','NAME','关联客人姓名','name','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','CUSNO','协议单位号','cusno','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','CUSINFO','协议单位名称','cusinfo','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','CARDNO','贵宾卡号','cardno','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','CARDINFO','贵宾卡名称','cardinfo','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','SALEID','销售代码','saleid','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','SALEINFO','销售员信息','saleinfo','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','DSC','折扣比率','dsc','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','REASON','折扣理由','reason','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','SRV','服务费比率','srv','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','TAX','税额','tax','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','DSCAMOUNT','折扣合计','dscamount','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','SRVAMOUNT','服务费合计','srvamount','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','TAXAMOUNT','税额合计','taxamount','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','AMOUNT','菜品金额','amount','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','AMOUNT1','菜品分摊额','amount1','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','AMOUNT2','菜品折扣分摊额','amount2','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','AMOUNT3','菜品服务费分摊额','amount3','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','MAXAMOUNT','上次打印总金额','maxamount','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','CHARGE','消费金额','charge','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','PAYCODE','付款代码 9001 或9001* 等','paycode','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','LASTNUM','记录明细行数','lastnum','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','LASTRNUM','记录打印行数','lastrnum','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','LASTPNUM','记录打印页数','lastpnum','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','CMSCODE','佣金代码','cmscode','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','INFO','主单备注信息','info','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','ACCNTINFO','挂账单位信息','accntinfo','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','QR_CODE','二维码','qr_code','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','ACCNT','单号','accnt','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','AMOUNT4','','amount4','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','AMOUNT5','','amount5','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','CREDIT','付款','credit','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','BAL','余额','bal','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','BILLNO','账单号','billno','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','EXTRA','标记','extra','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','PCREC','联单号','pcrec','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','RECEIPT_NO','发票号','receipt_no','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','RECEIPT_AMOUNT','发票金额','receipt_amount','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','TOACCNT','转账单号','toaccnt','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) values('2','-1','POS_MASTER','RESNO','预订单号','resno','','ADMIN','2013-05-06 15:32:30','ADMIN','2016-05-19 13:26:05');
insert into `log_info_config` (`hotel_group_id`, `hotel_id`, `entity_name`, `entity_column`, `descript`, `descript_en`, `sql_define`, `create_user`, `create_datetime`, `modify_user`, `modify_datetime`) 
SELECT t2.hotel_group_id,t2.id,t1.entity_name,t1.entity_column,t1.descript,t1.descript_en,t1.sql_define,t1.create_user,t1.create_datetime,t1.modify_user,t1.modify_datetime
FROM log_info_config t1,hotel t2
WHERE t1.hotel_id=-1;
DELETE FROM log_info_config WHERE hotel_id=-1;
