package com.greencloud.entity;


//Generated 2014-10-31 9:50:25 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
* TpStoreArticle generated by hbm2java
*/
public class PosStoreArticle extends OperationInfo {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = -6744981309169400775L;
	private String code;
	private String name;
	private String unit;
	private BigDecimal price;
	private BigDecimal maxQuan;
	private BigDecimal minQuan;
	private String sseg;
	private String sname;
	private String cseg;
	private String cname;
	private String oactmode;
	private String actmode;
	private String helpcode;
	private String standent;
	private String band;
	private Integer warning;
	private Integer lpno;
	private BigDecimal lprice;
	private String unit2;
	private BigDecimal equn2;
	private BigDecimal minprice;
	private String minsup;
	private BigDecimal maxprice;
	private String maxsup;
	private BigDecimal avprice;
	private String storage;
	private String quocode;
	private BigDecimal csnumber;
	private String csunit;
	private Integer csbili;
	private String cstype;
	private BigDecimal safeQuan;
	private Character valid;
	private String ref;
	private BigDecimal salePrice;
	private BigDecimal limitnumber;
	private String engName;
	private String engSname;
	private String engCname;
	
	private String isGroup;
	private String groupCode;
	private String codeType;
	public String getIsGroup() {
		return isGroup;
	}
	public void setIsGroup(String isGroup) {
		this.isGroup = isGroup;
	}
	public String getGroupCode() {
		return groupCode;
	}
	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode;
	}
	public String getCodeType() {
		return codeType;
	}
	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getUnit() {
		return unit;
	}
	public void setUnit(String unit) {
		this.unit = unit;
	}
	public BigDecimal getPrice() {
		return price;
	}
	public void setPrice(BigDecimal price) {
		this.price = price;
	}
	public BigDecimal getMaxQuan() {
		return maxQuan;
	}
	public void setMaxQuan(BigDecimal maxQuan) {
		this.maxQuan = maxQuan;
	}
	public BigDecimal getMinQuan() {
		return minQuan;
	}
	public void setMinQuan(BigDecimal minQuan) {
		this.minQuan = minQuan;
	}
	public String getSseg() {
		return sseg;
	}
	public void setSseg(String sseg) {
		this.sseg = sseg;
	}
	public String getSname() {
		return sname;
	}
	public void setSname(String sname) {
		this.sname = sname;
	}
	public String getCseg() {
		return cseg;
	}
	public void setCseg(String cseg) {
		this.cseg = cseg;
	}
	public String getCname() {
		return cname;
	}
	public void setCname(String cname) {
		this.cname = cname;
	}
	public String getOactmode() {
		return oactmode;
	}
	public void setOactmode(String oactmode) {
		this.oactmode = oactmode;
	}
	public String getActmode() {
		return actmode;
	}
	public void setActmode(String actmode) {
		this.actmode = actmode;
	}
	public String getHelpcode() {
		return helpcode;
	}
	public void setHelpcode(String helpcode) {
		this.helpcode = helpcode;
	}
	public String getStandent() {
		return standent;
	}
	public void setStandent(String standent) {
		this.standent = standent;
	}
	public String getBand() {
		return band;
	}
	public void setBand(String band) {
		this.band = band;
	}
	public Integer getWarning() {
		return warning;
	}
	public void setWarning(Integer warning) {
		this.warning = warning;
	}
	public Integer getLpno() {
		return lpno;
	}
	public void setLpno(Integer lpno) {
		this.lpno = lpno;
	}
	public BigDecimal getLprice() {
		return lprice;
	}
	public void setLprice(BigDecimal lprice) {
		this.lprice = lprice;
	}
	public String getUnit2() {
		return unit2;
	}
	public void setUnit2(String unit2) {
		this.unit2 = unit2;
	}
	public BigDecimal getEqun2() {
		return equn2;
	}
	public void setEqun2(BigDecimal equn2) {
		this.equn2 = equn2;
	}
	public BigDecimal getMinprice() {
		return minprice;
	}
	public void setMinprice(BigDecimal minprice) {
		this.minprice = minprice;
	}
	public String getMinsup() {
		return minsup;
	}
	public void setMinsup(String minsup) {
		this.minsup = minsup;
	}
	public BigDecimal getMaxprice() {
		return maxprice;
	}
	public void setMaxprice(BigDecimal maxprice) {
		this.maxprice = maxprice;
	}
	public String getMaxsup() {
		return maxsup;
	}
	public void setMaxsup(String maxsup) {
		this.maxsup = maxsup;
	}
	public BigDecimal getAvprice() {
		return avprice;
	}
	public void setAvprice(BigDecimal avprice) {
		this.avprice = avprice;
	}
	public String getStorage() {
		return storage;
	}
	public void setStorage(String storage) {
		this.storage = storage;
	}
	public String getQuocode() {
		return quocode;
	}
	public void setQuocode(String quocode) {
		this.quocode = quocode;
	}
	public BigDecimal getCsnumber() {
		return csnumber;
	}
	public void setCsnumber(BigDecimal csnumber) {
		this.csnumber = csnumber;
	}
	public String getCsunit() {
		return csunit;
	}
	public void setCsunit(String csunit) {
		this.csunit = csunit;
	}
	public Integer getCsbili() {
		return csbili;
	}
	public void setCsbili(Integer csbili) {
		this.csbili = csbili;
	}
	public String getCstype() {
		return cstype;
	}
	public void setCstype(String cstype) {
		this.cstype = cstype;
	}
	public BigDecimal getSafeQuan() {
		return safeQuan;
	}
	public void setSafeQuan(BigDecimal safeQuan) {
		this.safeQuan = safeQuan;
	}
	public Character getValid() {
		return valid;
	}
	public void setValid(Character valid) {
		this.valid = valid;
	}
	public String getRef() {
		return ref;
	}
	public void setRef(String ref) {
		this.ref = ref;
	}
	public BigDecimal getSalePrice() {
		return salePrice;
	}
	public void setSalePrice(BigDecimal salePrice) {
		this.salePrice = salePrice;
	}
	public BigDecimal getLimitnumber() {
		return limitnumber;
	}
	public void setLimitnumber(BigDecimal limitnumber) {
		this.limitnumber = limitnumber;
	}
	public String getEngName() {
		return engName;
	}
	public void setEngName(String engName) {
		this.engName = engName;
	}
	public String getEngSname() {
		return engSname;
	}
	public void setEngSname(String engSname) {
		this.engSname = engSname;
	}
	public String getEngCname() {
		return engCname;
	}
	public void setEngCname(String engCname) {
		this.engCname = engCname;
	}
	

	
}
